### PR TITLE
File association v2

### PR DESCRIPTION
**Pull request by lilymofu**
I decided on going with temporary directories, but this code is very buggy and WIP.  Do not push to master please.

### CODE REVIEW

**Review by bplin2 — COMMENTED** [review]
looks good so far - lemme know if you have any questions!

**Comment by lilymofu** [comment]
Finished all work needed to implement above.

**Review by bplin2 — DISMISSED** [review]
looks good- feel free to merge to master

**Review by FSSoar — COMMENTED** [review]
This looks fine to me

**Review by bplin2 — APPROVED** [review]

**Review by FSSoar — APPROVED** [review]
Looks fine

**Pull request merged**
